export const UPDATE_RATES = 'UPDATE_RATES';
export const CHANGE_SET_BY_USER_VALUE = 'CHANGE_SET_BY_USER_VALUE';

export const CHANGE_ACTIVE_CURRENCY_FROM = 'CHANGE_ACTIVE_CURRENCY_FROM';
export const CHANGE_ACTIVE_CURRENCY_TO = 'CHANGE_ACTIVE_CURRENCY_TO';